### ISSUE TITLE
CHANNEL JOIN FAILED: TypeError: Cannot read property 'stack' of undefined at Client.newDefaultKeyValueStore

### ISSUE THREAD

**Issue by germal** [HyperledgerHandsOn/trade-finance-logistics#48]
Hello,

I didn't manage to run successfully the application createTradeApp.js.
My environment is the following 
- Ubuntu Version 16.04
- Nodejs set to 9.8.0 as per README
- Hyperledger branch 1.1
- the versions of both fabric-client and fabric-ca-client installed are "1.1.2"  and grpc "1.10.1

-  I run successfully the Dev environment exercise .

- For the 9 container JS application I applied the following steps 
-   Delete client_certs, channel-artifacts, crypto-config folders in network        
./trade.sh generate -c tradechannel within network to generate the channel and crypto material
./trade.sh up to start the network  ( the 9 containers indeed start)
node createTradeApp.js

the error is 
---------------------
CHANNEL JOIN FAILED: TypeError: Cannot read property 'stack' of undefined
    at Client.newDefaultKeyValueStore.then.then.then.then (/root/go/src/github.com/hyperledger/trade-finance-logistics/middleware/join-channel.js:205:61)
    at <anonymous>
---------------------

Please help , I strongly want to learn from your book.
Thanks 
Germal

![docker ps](https://user-images.githubusercontent.com/47027729/51742440-0c9a4500-209a-11e9-892b-3f95b414ca44.jpg)
![error](https://user-images.githubusercontent.com/47027729/51742441-0c9a4500-209a-11e9-9eaa-028ca1b4cdf2.jpg)
[network.log.txt](https://github.com/HyperledgerHandsOn/trade-finance-logistics/files/2795794/network.log.txt)

**Comment by VRamakrishna** [comment]
Sorry for the late reply. You configuration and setup looks fine to me. From the error symptom, and what I see in the log you have attached, I'd guess the error is because of old/mismatched credentials or perhaps old channel artifacts, but you say you deleted them before you started.

Can you just confirm that you deleted the `client-certs` folder (wherever you configured that; by default, it should be in the `network` folder.) In your comment above, you say you deleted `client_certs` (with an underscore, not a dash.)

When I run the code with an identical configuration to yours and after cleaning everything up, everything runs fine, as it has since the code was developed, so I'm not sure what's different in your environment. When you retry, make sure you delete not just the folders on disk but also the running docker containers and the volumes.

**Comment by germal** [comment]
Hello , I just docker deleted and re-pulled the images of docker containers and the scripts work perfectly !
Thank you very much, your book is top quality , please let us know for our further courses and publications.

**Comment by VRamakrishna** [comment]
Great, glad to hear it worked, and that you find the book useful. We'll post updates on this repo whenever we have any.
