### ISSUE TITLE
Not able to get the desired output while running the app.js on browser.

### ISSUE THREAD

**Issue by nehajain20683** [HyperledgerHandsOn/trade-finance-logistics#77]
Not able to get the desired output while running the app.js on browser.
Please suggest, what is going wrong here.
![Screenshot from 2020-07-04 20-30-47](https://user-images.githubusercontent.com/61583732/86515253-4649b080-be35-11ea-998e-55f118a717fc.png)

**Comment by VRamakrishna** [comment]
You need to run app.js from the command line. And if you are running it within a VM, make sure the port (4000) is exposed to the host machine so you can query from the browser. You should use curl scripts from the command line instead of a browser as you will need to supply other options with the request.

See the latest branch: https://github.com/HyperledgerHandsOn/trade-finance-logistics/tree/release-1.4
Scripts can be found here: https://github.com/HyperledgerHandsOn/trade-finance-logistics/tree/release-1.4/application/client_scripts

**Comment by VRamakrishna** [comment]
Also, this is a fairly old project at this point and we are nor maintaining it any more. We have instead been working on a new and improved project that works for the latest version of Fabric (version 2). This should be released within a month or so; watch out for notifications on these pages.

**Comment by nehajain20683** [comment]
Thank you so much for your reply. Thank you.
